### ISSUE TITLE
No longer works after upgrade to Directus v11

### ISSUE THREAD

**Issue by JSDA123** [rezo-labs/directus-extension-schema-management-module#15]
I found this module stopped working after upgrading to Directus 11.

The module appears installed and enabled, but the menu item is gone. Removing and re-installing does not resolve the issue.

I tried various URLs to see if the issue was just a missing menu link, however I could find nothing at admin/schema or admin/schema-management-module or admin/schema-management-module/schema

**Comment by duydvu** [comment]
Hi @JSDA123 , I'm having other work these days so I don't have much time to update this extension. But I will try to check it out within this week.

Thanks for reporting.

**Comment by duydvu** [comment]
I have updated the extension, please upgrade to ver 2.0.1

**Comment by JSDA123** [comment]
Thank you, it seems to work perfectly!
