### ISSUE TITLE
Add management for Roles & Permissions

### ISSUE THREAD

**Issue by pgegenfurtner** [rezo-labs/directus-extension-schema-management-module#2]
To make this package complete, it would be really helpful to include roles and permissions in the export / import.

I know this technically is not schema, but is a key component for a full dev / prod sync.

**Comment by duydvu** [comment]
Great idea! It will definitely be helpful for all of us.

**Comment by xu4wang** [comment]
> To make this package complete, it would be really helpful to include roles and permissions in the export / import.
> 
> 
> 
> I know this technically is not schema, but is a key component for a full dev / prod sync.

@pgegenfurtner I am looking for a way to manage schema/roles/permissions in a git repo too.  feeling too easy to make mistake by configuring by clicking on the GUI each time
