### ISSUE TITLE
Allow folder collections to be exported.

### ISSUE THREAD

**Issue by luochuanyuewu** [rezo-labs/directus-extension-schema-management-module#3]
When i exporting my scheme from ui. i can't select "folder" collection.
when i importing my schema from another instance. i got following error:
Invalid foreign key for field "group" in collection "directus_collections" when importing.

**Comment by duydvu** [comment]
Thanks for your suggestion. This is a good QOL feature.

Currently, if you want to export collections from a group, you need to create the group with the exact same name in the destination Directus before importing.

**Comment by jjeising** [comment]
This is a big issue for us, as grouping does not seem to be supported at all. The import of our schema fails on the first table, as the required collection was not created yet. Example:
```json
{
    "collections": [
        {
            "collection": "agenda_categories",
            "meta": {
…
                "group": "agenda",
   …
            },
            "schema": {}
        },
…
        {
            "collection": "agenda",
            "meta": {
…
            },
            "schema": {}
        },
```
