### ISSUE TITLE
install on directus docker

### ISSUE THREAD

**Issue by petrosmm** [rezo-labs/directus-extension-schema-management-module#9]
for my directus docker instance (10.6.1), i had to install using the following:
```
yarn add argon2 2> /dev/null
yarn add directus-extension-schema-management-module
reboot
```

Unfortunately it needs argon2, I don't know why. And furthermore, it errors out while installing argon2 hence the redirected errors. This is more of an afterthought but wondering if there's a way to shed light on this.

**Comment by almereyda** [comment]
We're running this from

```Dockerfile
FROM directus/directus:10.8.2

USER root
RUN corepack enable
USER node

RUN pnpm install \
      directus-extension-api-docs \
      directus-extension-schema-management-module
```

I had found the `corepack` directive somewhere in the documentation. Maybe it does what your `argon2` requirement solves, too?
